use_frameworks!

target 'SLTopMiniApps_Example' do
  pod 'SLTopMiniApps', :path => '../'

  target 'SLTopMiniApps_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
